"""add simulations and simulation_entries

Revision ID: 3980e93a3db7
Revises: 
Create Date: 2026-08-25 19:22:37.905057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3980e93a3db7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capital', sa.Float(), nullable=False),
    sa.Column('entry_1a', sa.Float(), nullable=False),
    sa.Column('entry_1b', sa.Float(), nullable=False),
    sa.Column('second_entry', sa.Float(), nullable=False),
    sa.Column('payout_ratio', sa.Float(), nullable=False),
    sa.Column('target_profit', sa.Float(), nullable=False),
    sa.Column('max_entries', sa.Integer(), nullable=False),
    sa.Column('wall_hit', sa.Boolean(), nullable=False),
    sa.Column('wall_required_stake', sa.Float(), nullable=True),
    sa.Column('wall_balance_available', sa.Float(), nullable=True),
    sa.Column('losses_survived', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_simulations'))
    )
    op.create_table('simulation_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=8), nullable=False),
    sa.Column('stake', sa.Float(), nullable=False),
    sa.Column('cumulative_loss', sa.Float(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('balance_if_win', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], name=op.f('fk_simulation_entries_simulation_id_simulations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_simulation_entries'))
    )
    op.create_index(op.f('ix_simulation_entries_simulation_id'), 'simulation_entries', ['simulation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulation_entries_simulation_id'), table_name='simulation_entries')
    op.drop_table('simulation_entries')
    op.drop_table('simulations')
    # ### end Alembic commands ###
