"""make entry_1b nullable

Revision ID: 3f43cca953db
Revises: 30bb9e816ea3
Create Date: 2026-08-27 13:43:09.821550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f43cca953db'
down_revision: Union[str, Sequence[str], None] = '30bb9e816ea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.alter_column('entry_1b',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.alter_column('entry_1b',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
