"""add run_group to simulations

Revision ID: 50d32bbc3552
Revises: 5b89a92224dc
Create Date: 2026-08-26 19:31:42.722728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50d32bbc3552'
down_revision: Union[str, Sequence[str], None] = '5b89a92224dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('run_group', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_simulations_run_group'), ['run_group'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulations_run_group'))
        batch_op.drop_column('run_group')

    # ### end Alembic commands ###
