"""add strategy to simulations

Revision ID: 5b89a92224dc
Revises: d1e01e14819b
Create Date: 2026-08-26 19:18:25.682295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b89a92224dc'
down_revision: Union[str, Sequence[str], None] = 'd1e01e14819b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strategy', sa.String(length=20), server_default='adder_profit', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.drop_column('strategy')

    # ### end Alembic commands ###
