"""make second_entry nullable

Revision ID: d1e01e14819b
Revises: 3980e93a3db7
Create Date: 2026-08-26 18:56:48.848525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e01e14819b'
down_revision: Union[str, Sequence[str], None] = '3980e93a3db7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.alter_column('second_entry',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.alter_column('second_entry',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
